# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Autograde

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
#   - name: Install dependencies
#     run: |
#       python -m pip install --upgrade pip
    - name: Test with Autograde
      run: python autograder.py | tee result.txt
    - name: Evaluate Grades
      run: |
        # Filter out all lines containing the actual grade
        cat result.txt | grep -e '###' | tee grade.txt
